version: 2.1

jobs:
  not-windows-stuff:
    machine:
      docker_layer_caching: true  # this is expected to fail, just testing what the message is
    steps:
    - run:
        command: echo asdf

workflows:
  workflow:
    jobs:
      - not-windows-stuff
