version: 2.1

jobs:
  windows-stuff:
    machine:
      image: windows-server-2019
      docker_layer_caching: true  # this is expected to fail, just testing what the message is 
    resource_class: windows.medium
    working_directory: c:\\\\cache
    shell: powershell.exe -NoProfile -ExecutionPolicy Bypass
    steps:
    - run:
        command: echo \"Welcome to Windows on CircleCI\"
    - run:
        command: systeminfo

workflows:
  workflow:
    jobs:
      - windows-stuff
